### ISSUE TITLE
configuring "for" and "not-for" for field mapping

### ISSUE THREAD

**Issue by ankusinha23** [solidify/jira-azuredevops-migrator#1000]
here is the config where for bug descripton from JIRA should be migrated to repro steps and for other work item type its should bbe mapped to accptance criteria
[DLA-54.json](https://github.com/solidify/jira-azuredevops-migrator/files/14641640/DLA-54.json)
[jira-export-log-240319-011435.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14641641/jira-export-log-240319-011435.txt)
but getting warning and items are not migarting to acceptance criteria as well as repro steps

**Comment by Alexander-Hjelm** [comment]
Hi @ankusinha23 !

We would need to look closer at your `config.json` file to say for sure what the issue is, but it seems that you have multiple mappings set up for AppectanceCritera and ReproSteps, and it seems like multiple mappings for the same field are acting on the same WorkItemType.

In general, `for` and `not-for` refers to the ADO Work Item Types. `for` will apply the mapping to any work item with any of the specified types, and `not-for` will apply the mapping to any work item which does not belong to the specified types.

I hope that shed some light on your situation. Otherwise you are welome to attach your config file here.
