### ISSUE TITLE
Close date doesn't migrate

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#149]
The original issue #117  was closed, but I was able to do it by a script, updating work item with bypass_rules=True

result = wit_client.update_work_item(patch_document, itemId, project_name, validate_only=False, bypass_rules=True)

can it be done on your side?

**Comment by madkoo** [comment]
@AmitNaveh23 we do use the bypass_rules=True in our current implementation but due to the limitations of the SDK we use the closed date cannot be edited. At the moment we are not able to do this on our side because of that I am closing this issue. If you have any other questions feel free to contact us.
