### ISSUE TITLE
Custom fields do not export from Jira

### ISSUE THREAD

**Issue by apiotuch** [solidify/jira-azuredevops-migrator#184]
I have been trying for several days to export a project that has a couple custom fields for a custom bug ticket. When I look in the json files representing the exported tickets, there is no data for any custom fields. I have tried using **_"name"_**, **_"id"_**, for **"source-type"**, and **_"Custom Field Name"_**, **_"1234"_**, **_1234_**, for **"source"** in the config file. Nothing seems to get it to export. I only ever get the built in description along with some other built in fields to export. Do I need to include in the JQL query explicitly to export each custom field? Or is there a catch all to export every field for every ticket? Is there some setting in Jira that I need to enable to allow for custom field data to export? 

Using Jira cloud, importing to Azure DevOps.

**Comment by madkoo** [comment]
@apiotuch Can you provide more details on how your config for custom fields looks like? 
Have you checked our config documentation and FAQ section?

**Comment by apiotuchAoD** [comment]
@madkoo I have been using the sample config-agile.json file and using config documentation. I don't know if I saw the FAQ section.

I have tried exporting from a new sample project with custom fields and that seemed to export with no issues.

However the project I am trying to migrate does not seem to export custom fields at all.

this is one of the objects I added to the field array:
{
     "source-type": "name",
     "source": "Expected Result",		
     "target": "Custom.ExpectedResult",
     "mapper": "MapRendered",
     "for": "Bug"
}
Other objects have a similar structure. I have tried excluding the "for" parameter, as well as changing the order of the properties, but nothing seems to work. Built in fields export.

I tried placing this at the end and at the beginning of the array, but it doesn't make any difference.

**Comment by apiotuchAoD** [comment]
@madkoo I have looked at the FAQs now and I have read them before.

**Comment by madkoo** [comment]
@apiotuchAoD  what type of custom field it is? Does it contain HTML and is that why you are using the MapRendered mapper?

**Comment by apiotuchAoD** [comment]
It is a WikiRenderer. It seems there are only 2 options available for Renderers, Wiki and Text. There is no HTML. I removed the mapper property from the object definition and it was able to get some of the Custom Fields now. Should be working for the rest.

Another topic, is there anyway of mapping Jira ticket numbers to Azure Work Item ID? Or retaining ticket creation date?

**Comment by madkoo** [comment]
@apiotuch, unfortunately, it is not possible to map the Jira Ticket number to Azure Work Item Id, because it is auto-generated. But the creation date should match what you have in Jira.

**Comment by apiotuchAoD** [comment]
@madkoo When I import ReproSteps, I am not using a mapper and it ends up taking a numbered list and creating a paragraph of text. Is there a mapper for WikiRenderer? Or do I need to do something custom with extracting the list from a string, and converting it into an array?

**Comment by madkoo** [comment]
@apiotuch  For ReproSteps and Description fields I would suggest using MapRendered mapper

**Comment by apiotuchAoD** [comment]
MapRendered does not work for WikiRenderer, so my custom field for ReproSteps does not export from Jira if I use MapRendered.

**Comment by apiotuchAoD** [comment]
@madkoo 
![image](https://user-images.githubusercontent.com/61207513/75195978-db160200-570f-11ea-9559-804a6d71c997.png)

No errors or warnings are thrown when I include "mapper": "MapRendered" regardless if I specify target to a custom field in Azure or to "target": "Microsoft.VSTS.TCM.ReproSteps". No object is created in the json file. 

If I simply omit "mapper": "MapRendered", then an object is created in the json file. Then, when importing in Azure, the list of steps that were exported from Jira will not be listed line by line, but just as a paragraph.

Depending on the Jira view, there is different formatting. Above is a new ticket, below is an example of editing an existing ticket

![image](https://user-images.githubusercontent.com/61207513/75196133-37792180-5710-11ea-9c13-d1409b89f416.png)

When not using mapper, then the exported ticket will list steps like this in a single line, i.e. 
"Value": "1. Do step 1\n\n2. Do Step 2\n\n3.Do step 3"

when importing into Azure it will be in paragraph form:
1. Do step 1 2. Do step 2 3. Do step 3

instead of (expected)
1. Do step 1 
2. Do step 2 
3. Do step 3

However sometimes in exports as:
"Value": "# Do step 1\n\n2. Do Step 2\n\n3.Do step 3"
note the first item is not numbered but has a # instead, but the rest retain their list numbers

**Comment by madkoo** [comment]
This was indeed a bug and we have fixed this. The fixed should go out with the next release.

**Comment by apiotuchAoD** [comment]
I imagine covid-19 has impacted development and testing for this migrator project. Will there be any updated in the near future? I am still waiting for this fix as I am still working.

**Comment by madkoo** [comment]
@apiotuch  the fix for this is now released, you can use the "MapRendered"  mapper. I'm closing the issue, if you still experience problems then feel free to contact us.
