### ISSUE TITLE
Getting a warning with respect to user id

### ISSUE THREAD

**Issue by prasathe-git** [solidify/jira-azuredevops-migrator#220]
Hello All,

I am getting below warning, not sure what this is about

Email is not public for user '5db16dc89703bc0c2d27e0e9' in Jira, using usernameOrAccountId '5db16dc89703bc0c2d27e0e9' for mapping.

I have the user1.txt available with all the user names exported from jira in following format

5db174105304a60c3a767aff=username@domainname

Can you please suggest what is this?

Thanks

Pradyumna Sathe

**Comment by madkoo** [comment]
@prasathe-git Jira Cloud has changed its API on what user data can be retrieved because of GDPR.
From Jira Cloud to get user email the accountId is now used to get the user's email address. The requirement for that to get that is that user should change their email public in their profile to use email to email mapping. Otherwise, accountId to email mapping should be used if user mapping is needed.   
The answer to your question is that the tool is trying to get the email for that user with accountID but as the email is not public the information cannot be retrieved so we use accounted instead of in user mapping.
