### ISSUE TITLE
Cant transfer components/fixVersions/versions

### ISSUE THREAD

**Issue by cris-b** [solidify/jira-azuredevops-migrator#40]
The components, fixVersions and versions fields are arrays of objects, whatever I try I cant get these to populate in the exported json.

**Comment by MOlausson** [comment]
@cris-b can you share an example of the field definition in Jira and the config file you have for the migration mapping?

**Comment by cris-b** [comment]
sure, configuration:

      {
        "source": "versions",
        "target": "Microsoft.VSTS.Build.FoundIn",
        "source-type": "name"
      },
      {
        "source": "fixVersions",
        "target": "Microsoft.VSTS.Build.IntegrationBuild",
      }

jira response content:

    "fields": {
    "fixVersions": [{
      "self": "https://test:8443/rest/api/2/version/47829",
      "id": "47829",
      "description": "Major update",
      "name": "RPC_METL_RELEASE_02.00.00",
      "archived": false,
      "released": true,
      "releaseDate": "2016-03-29"
    }],
    "versions": [{
      "self": "https://kmlwgunxscm.grpitsrv.com:8443/rest/api/2/version/43922",
      "id": "43922",
      "description": "First Complete Release",
      "name": "RPC_METL_RELEASE_01.00.00",
      "archived": false,
      "released": true,
      "releaseDate": "2015-10-30"
    }],
    "components": [{
      "self": "https://kmlwgunxscm.grpitsrv.com:8443/rest/api/2/component/10046",
      "id": "10046",
      "name": "Panel processing",
      "description": "The Panel processing stream"
    }]
    }

**Comment by MOlausson** [comment]
Ok, got it. @cris-b how would you expect the result in Azure DevOps to look? A formated list? Azure DevOps doesn't have a multi-select list by default, is that how you would like to see it?

**Comment by cris-b** [comment]
i created a pull request for this, i guess a comma separated list (as it would look in jira) is all you can do as the field is just a string.

for components i'm not sure where the most appropriate place is for them.  I'm guessing converting to tags would probably suit, but what if you have tags and labels on a jira?  at the moment i dont think there is a way to merge multiple jira fields to one devops field

**Comment by srikanthachutuni** [comment]
**@MOlausson** , 

I do have the same issue described by **@cris-b**.

Source: JIRA field **fixVersions** is of type **array**. 
Target: Azure DevOps field **Microsoft.VSTS.Build.IntegrationBuild** is of type **String**
![image](https://user-images.githubusercontent.com/46751968/55990491-c8b8e400-5c75-11e9-91c4-2389b6e93360.png)

In the JSON file I have done the mapping as below. Since the source field type is **array** and the target field type is **String**, I am not getting the source field value after migration.
	  {
        "source": "fixVersions",
        "target": "Microsoft.VSTS.Build.IntegrationBuild",
          },

**I would like to see single OR multi-select drop down list by default in Azure DevOps.**

**Comment by MOlausson** [comment]
@srikanthachutuni, @cris-b thanks for the suggestions and examples. I'll try to make the configurable but if we change the proposed PR to use semicolons instead of commas then it will map nicely to https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-extensions-multivalue-control as a way to get it looking more like the Jira issue. I'll have a look, at least approve the PR that seems to work.

**Comment by MOlausson** [comment]
Fixed in release 2.2.x

**Comment by kmuthukumar-rp** [comment]
@MOlausson @cris-b @srikanthachutuni Can you please explain how we can map components, fixversions and affected versions. Do we need to specify 'source-type: name' which is for custom field I guess and which field in Azure it can map to. Is it adding as tags or setting a string value or a drop down. I would like to understand how this can be mapped. Can you please prvide JSON for it. Thank you.

**Comment by kmuthukumar-rp** [comment]
If I like to map components to tags as well as the existing tags mapping (from labels), will I be able to do that. Thanks.

**Comment by rambaliga** [comment]
Hi,

We are now running into this same issue where we cannot migrate components, fix versions. Is this something that can be configured through solidify?
