### ISSUE TITLE
Links are not imported into ADO for cross projects

### ISSUE THREAD

**Issue by MuthumariPonnusamy** [solidify/jira-azuredevops-migrator#478]
While migrating work items of 2 different projects into single project in ADO, their corresponding links are not imported into ADO.

**Comment by MuthumariPonnusamy** [comment]
Please find the cofig files and Json files.
[cross projects.zip](https://github.com/solidify/jira-azuredevops-migrator/files/9000242/cross.projects.zip)

**Comment by Alexander-Hjelm** [comment]
@MuthumariPonnusamy Not yet sadly. Since this feature is out-of-scope for what we originally intended for the tool, I can't give an estimate on how long it will take until we fix it.

In the meantime, we always welcome the community to implement it :)

If we can help you with your migration, you are always welcome to make a business inquiry to Solidify AB, Sweden.

**Comment by Alexander-Hjelm** [comment]
Closing as we will not be working on this
