### ISSUE TITLE
Type Mapping issues for customized Jira types

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#528]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/527

<div type='discussions-op-text'>

<sup>Originally posted by **omustapasa** September  1, 2022</sup>
Hello all,

My organization has an unorthodox JIRA setup where certain types in JIRA are customized in a way that they renamed:
''User Story'' to ''Story - Development'' and 
''Task'' to ''Task - Development''

And I am receiving such an error:
**" .... with Jira type 'Story - Development'. Item was not exported which may cause missing links in issues referencing this item."**

I have tried to export from JIRA today following the guide lines however below mapping does not seem to work.
`"type-map": {
    "type": [
      {
        "source": "Story - Development",
        "target": "Feature"
      },
      {
        "source": "Task - Development",
        "target": "User Story"
      },`

Is there a way for me to get over this problem without having to update the issue types on JIRA historically?</div>

**Comment by Alexander-Hjelm** [comment]
@omustapasa, It should be possible to migrate any issues, no matter what the type name. Can you include your config file and migration log in a comment on this issue?

**Comment by omustapasa** [comment]
Hi @Alexander-Hjelm,

I have just found the problem and it was totally on my side.
Instead of using a config file on the root folder as the executable, I decided to use one of the config files in the Samples folder and forgot to copy it to the root folder after the changes.

Upon finding my own problem now I am having 

[E][14:40:16] Unexpected migration error.
[System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex

which is a totally different issue hence maybe we can close this ticket I have just created.

Thank you for your super fast reply!

**Comment by Alexander-Hjelm** [comment]
That's fine, we just have the habit of keeping all support contact through GitHub Issues, since it has better traceability than discussions :)

Your latest problem is a known bug, which has been fixed in the latest (but unreleased) version of the tool. You can either pull the latest untested version from master, and build the tool yourself, or wait until the next prerelease (probably in a week or two) :)

See: https://github.com/solidify/jira-azuredevops-migrator/issues/528
