### ISSUE TITLE
Jira export should not write empty revisions

### ISSUE THREAD

**Issue by moerketh** [solidify/jira-azuredevops-migrator#545]
**Is your feature request related to a problem? Please describe.**
The current jira export (both released and master) is writing empty revisions to the issue.json file. In my current small test scenario I'm exporting 70 issues, generating ~28k revisions, where ~25k are empty.

With an empty I mean the following:
```
{
      "Author": "JIRAUSER",
      "Time": "2021-01-04T17:41:13.477+01:00",
      "Index": 35,
      "Fields": [],
      "Links": [],
      "Attachments": [],
      "AttachmentReferences": false
},
```

This happens when there is a revision in Jira (for example the "Rank" field has been updated). But this field is not included in the FieldMap. This will generate an empty WorkItemRevision. I have not checked what the workitem import tool does exactly with this empty revision, but it is taking a lot of time for what is essentially not a change.

**Describe the solution you'd like**
It would be better if the Jira export tool does not write the empty revisions to the issue.json file. This also saves me a lot of time. For 70 items the export completes in ~3 minutes instead of ~4 minutes with the empty revisions. It easily saves me hours on the workitem import.

**Describe alternatives you've considered**
I'm currently running a script to remove the empty revisions before importing.

Please let me know if I am missing something here.

**Comment by Alexander-Hjelm** [comment]
@moerketh 
I had a talk with Madis and we looked at your PR together. We think this issue is a sign that you are not mapping all your data properly. Check your config file and compare it to your issue history in JIRA, as well as the exported revisions. You will find that if you are using the sample configs, they are not set up to migrate all the data, including (but not limited to) custom fields.

The current implementation solves it by creating empty revisions if it doesn't know how to map certain fields, because once you start deleting revisions, you are changing the history without consideration to unmapped fields that you might be interested..

We will not merge your PR right now because of this. Check your data and make sure that this is not because of missing fields in the mapping config first :)

**Comment by moerketh** [comment]
Thanks for the feedback! I am aware I have not mapped all fields in the config and I agree this is the cause of the empty revisions. 

However I do not see any benefit of writing the empty revisions to file. Are you saying you are looking at the exported json file to identify missing fieldmappings?

**Comment by Alexander-Hjelm** [comment]
I think that in a typical use case you would want to migrate all (or at least most) or your available data, so if you have enough empty revisions to cause a significant performance degredation, chances are that something funky is going on. For instance, you could actually be skipping a lot of crucial data, and having empty revisions with timestamps in your export data helps you pin the issue down, when logging every single missing field would cause an overflow of information in the logs.

I would argue that your fix covers a niche use case. Is it justifiable to convolute the config file and docs with properties to cover up niche use cases? It will be a tradeoff between user friendliness and performance in the end.

At least this is how I see it, but maybe you have other arguments that make more sense? :)
________________________________

**Comment by moerketh** [comment]
Thanks for the clarification! Appreciate the perspective.

Having the json between the export and import makes it easy to script changes for situations like this. I can see that is a reason for not having too many options in the tool. Too many options might also become confusing, agreed.

This type of migration (by API calls) is fairly slow. With any data set beyond a trivially small one it is going to take a long time to migrate. There are several ways to handle that. Not including all fields in the migration seems like a valid option to consider.

Sure you can correlate the empty revisions to Jira changes. The only data you have for that is the timestamp. You'd have to check all of them to make sure you are not missing a field. That does not scale well. Perhaps there should be a "validate" stage where the tool would check if all fields are actually mapped and log warnings for fields\types\links that are not mapped.

FYI, I'm currently not at a migration that is "good enough". I'm okay with leaving this as-is, and focus on the remaining bugs.

**Comment by omustapasa** [comment]
Even-though I reason with all the comments here, I will be manually applying this change (as per the PR) to be able to continue my migration on my personal case where I have fields which were added and removed and they appear in the revision history.
Such revisions result in empty revisions on the exported JSON which during import process fails and throws exceptions causing ADO Work Item History not fully migrated as in:

Initial state of the ticket is "New"
Second state of the ticket is "In Progress"
There are a few revisions (workflow updates or changes) which are the empty revisions in the exported file (I do not need those at all)
Last state of the ticket is "Done""

migration fails due to the empty revisions and work items are left with their last successful save state which is ''In Progress'' where the expected is ''Done''.

Even the revisions are not supposed to be empty maybe applying this solution can help in certain cases.

**Comment by pengliangyou** [comment]
> Even-though I reason with all the comments here, I will be manually applying this change (as per the PR) to be able to continue my migration on my personal case where I have fields which were added/removed or workflow related changes on Jira. They all appear in the revision history. Such revisions result in empty revisions on the exported JSON which during import process fails and throws exceptions causing ADO Work Item History not fully migrated as in:
> 
> Initial state of the ticket is "New" Second state of the ticket is "In Progress" There are a few revisions (workflow updates or changes) which are the empty revisions in the exported file (I do not need those at all) Last state of the ticket is "Done""
> 
> migration fails due to the empty revisions and work items are left with their last successful save state which is ''In Progress'' where the expected is ''Done''.
> 
> Even the revisions are not supposed to be empty maybe applying this solution can help in certain cases.

hi i met this issue too. the final state is wrong.
could i delete the empty revisions manually?

**Comment by moerketh** [comment]
Yeah, it's probably a good idea to close the attached PR in favor of a standalone script for those who have a use-case for it.

@pengliangyou Yes, you could remove them manually if you make sure the revision indexes are still sequential. Or give this PowerShell script a try:
```
param (
    [string]$InputDir = 'c:\jira-azuredevops-migrator\output'
)

$totalremovedcount = 0
$totalremaincount = 0
$exportedIssues = Get-ChildItem "$InputDir\*.json"
foreach($issue in $exportedIssues) {
    write-output "Parsing $issue"
    $issuecontent = Get-Content $issue | ConvertFrom-Json
    
    $startCount = $issuecontent.Revisions.Count
    if($null -ne $issuecontent.Revisions ) {
        $issuecontent.Revisions = ($issuecontent.Revisions | Where-Object { 
            $_.Fields -ne $null -or 
            $_.Links -ne $null -or 
            $_.Attachments -ne $null
        })
    }
    
    write-output "Rewriting revision index"
    $remaincount = $issuecontent.Revisions.Count
    for([int]$i=0; $i -lt $remaincount; $i++) {
        $issuecontent.Revisions[$i].Index = $i
    }
    
    $totalremovedcount += ($startCount - $remaincount)
    $totalremaincount += $remaincount
    $issuecontent | ConvertTo-Json -depth 99 | Out-File $issue
}
Write-Output "Removed $totalremovedcount empty revisions, $totalremaincount revisions remain"
```

This should read the exported json files and remove all the empty revisions. I haven't tested this script a lot but I don't see any obvious issues with it either.

**Comment by Alexander-Hjelm** [comment]
This feature was implemented in https://github.com/solidify/jira-azuredevops-migrator/commit/e5c8ba19189afb50be824b1869a246ad7afb9788

Closing this issue
