### ISSUE TITLE
WorkItem-Import: Revisions and attachments are created with the token owner's account

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#547]
Originally posted by @omustapasa in https://github.com/solidify/jira-azuredevops-migrator/issues/443
I have recently checked-out the latest code from master.
Exporter seems to produce the correct results as per the JSON files generated.
Importer however creates all related history and attachments with the same account the application runner uses (token owner in my case)

I am not sure if this is caused by a change on ADO API or it is somewhat a side effect of having some preview features on/off and/or used access token for importer execution not having certain rights.

It would be great to have it resolved as my migration is quite dependent on this at this stage.
I would like to know if this is a limitation as per ADO API or something else.

**Comment by Alexander-Hjelm** [comment]
@omustapasa, does this problem happen for comments as well? Or are comments assigned to the correct user?

**Comment by Alexander-Hjelm** [comment]
Needs to be fixed ahead of the 3.0 release

**Comment by omustapasa** [comment]
> @omustapasa, does this problem happen for comments as well? Or are comments assigned to the correct user?

It happens for comments as well.
Regardless where you look at the comments and other history (Details at the bottom of the page or history tab) token owner is the owner of all actions.

If this is a change in the Azure Boards API I would suggest adding the original comment owner in the comments section at least as in : "<original comment owner> says: <original comment text>" format.

**Comment by Alexander-Hjelm** [comment]
@omustapasa OK! noted.

It's most likely a failure in the code somewhere, as this has worked as expected before. If you're in a hurry, you can grab the latest stable release from here: https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v2.3.117

**Comment by Alexander-Hjelm** [comment]
@omustapasa I have been unable to reproduce the issue, when I run the a fresh build of master, everything seems fine and the history entries and comments are created by the correct author.

Have you checked the export log? Does it complain that there are missing user mappings? It might be that if it cannot resolve the author of the change/comment, it will default to the author of the issue, in this case the token owner.

Relabeling this as a support issue

**Comment by Alexander-Hjelm** [comment]
Screenshot for reference. Here you can see that the original authors are added. The only mention of me is adding/deleting links and creating the issue. These operations must be made by the token owner.

![image](https://user-images.githubusercontent.com/10683896/192263532-0f619e95-c01d-4e95-9f47-098dda0eca0e.png)

**Comment by omustapasa** [comment]
Hello @Alexander-Hjelm,

I can tell you not all users from JIRA are available on ADO and user.txt as we had coworkers who left the organization.
For their accounts I used the default account option on the user.txt as in
`*=JiraAzureDevOps@domain.com`

However I still see my personal account as the comment and attachment owner where all the user stories, epics are have their own respective owners assigned.
P.S: Not all users are assigned to the available team for the project on ADO however since all other assignations work as expected I do not see this being a problem as per same users are the ones making the comments which is not assigned correctly.

Sadly for my case the situation is not what you are presenting. Maybe there's an issue with my user.txt and its location.
Currently my users.txt is located in the same folder as where the jira workitems are being exported and I am using the same folder for the import (I am using the same config for the importer copy/paste)

> It might be that if it cannot resolve the author of the change/comment, it will default to the author of the issue, in this case the token owner

It might be the case as I have quite a lot of users removed or inactive on JIRA but I can not reason why the existing users are present as the "Assigned To'' but not in the comments section at all.

- Is the users.txt file case sensitive for email accounts?
- Does it have to be present somewhere else for the importer to read for comments?
- Does not the default mapping in users.txt work for non existent users for comments? I could simply run the script with that robotic user anyways but it is interesting that it defaults to the token owner rather than the default which is set in the users.txt

Not sure how I can debug this and move forward, I am losing the whole meaning of my data without the comments and its not good.


For reference here is my config:
`{
  "source-project": "GOT",
  "target-project": "TESTPROJECT",
  "query": "project = 'GOT' AND Sprint='Sprint 62' ORDER BY created DESC",
  "using-jira-cloud": true,
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Info",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "Gotham",
  "base-iteration-path": "",
  "ignore-failed-links": true,
  "process-template": "Scrum",
  "link-map": {
    "link": [
      {
        "source": "Epic",
        "target": "System.LinkTypes.Hierarchy-Reverse"
      }
    ]
  },
  "type-map": {
    "type": [
      {
        "source": "Epic",
        "target": "Feature"
      },
      {
        "source": "Story - Development",
        "target": "Product Backlog Item"
      },
      {
        "source": "Bug",
        "target": "Bug"
      },
      {
        "source": "Task - Development",
        "target": "Task"
      },
      {
        "source": "Sub-task Development",
        "target": "Task"
      }
    ]
  },
  "field-map": {
    "field": [
      {
        "source": "Sprint",
        "source-type": "name",
        "target": "System.IterationPath",
        "mapper": "MapSprint"
      },
      {
        "source": "summary",
        "target": "System.Title",
        "mapper": "MapTitle"
      },
      {
        "source": "assignee",
        "target": "System.AssignedTo",
        "mapper": "MapUser"
      },
      {
        "source": "description",
        "target": "System.Description",
        "mapper": "MapRendered"
      },
      {
        "source": "priority",
        "target": "Microsoft.VSTS.Common.Priority",
        "mapping": {
          "values": [
            {
              "source": "1",
              "target": "1"
            },
            {
              "source": "2",
              "target": "2"
            },
            {
              "source": "3",
              "target": "3"
            },
            {
              "source": "4",
              "target": "4"
            },
            {
              "source": "5",
              "target": "5"
            },
            {
              "source" : "High",
              "target": "1"
            },
            {
              "source" : "Medium",
              "target": "2"
            },
            {
              "source" : "Low",
              "target": "3"
            }
          ]
        }
      },
      {
        "source": "labels",
        "target": "System.Tags",
        "mapper": "MapTags"
      },
      **{
        "source": "comment",
        "target": "System.History",
        "mapper": "MapRendered"
      },**
      {
        "source": "status",
        "target": "System.State",
        "mapping": {
          "values": [
            {
              "source": "Candidate",
              "target": "Candidate"
            },
            {
              "source": "Reopened",
              "target": "Reopened"
            },
            {
              "source": "Development",
              "target": "Development"
            },
            {
              "source": "Documentation",
              "target": "Documentation"
            },
			      {
              "source": "Under Investigation",
              "target": "Under Investigation"
            },
            {
              "source": "Functional specification",
              "target": "Functional Specification"
            },
            {
              "source": "Technical specification",
              "target": "Technical Specification"
            },
            {
              "source": "UI/UX design",
              "target": "UI/UX Design"
            },
            {
              "source": "Waiting for client approval",
              "target": "Waiting for Client Approval"
            },
            {
              "source": "Quality Assurance",
              "target": "Quality Assurance"
            },
            {
              "source": "Ready to Go",
              "target": "Ready to Go"
            },
            {
              "source": "Internal Review",
              "target": "Internal Review"
            },
            {
              "source": "Backlog",
              "target": "Backlog"
            },
            {
              "source": "Waiting for Internal",
              "target": "Waiting for Internal"
            },
            {
              "source": "Waiting for external",
              "target": "Waiting for External"
            },
            {
              "source": "In Progress",
              "target": "In Progress"
            },
            {
              "source": "Pending Production Release",
              "target": "Pending Production Release"
            },
            {
              "source": "Done",
              "target": "Done"
            },
            {
              "source": "Canceled",
              "target": "Cancelled"
            }
          ]
        }
      },
      {
        "source": "Story points remaining",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.StoryPoints"
      },
      {
        "source": "Story point estimate",
        "source-type": "name",
        "target": "Microsoft.VSTS.Scheduling.Effort"
      },
      {
        "source": "timeestimate",
        "target": "Microsoft.VSTS.Scheduling.RemainingWork",
        "mapper": "MapRemainingWork"
      },
      {
        "source": "Description",
        "target": "Microsoft.VSTS.TCM.ReproSteps",
        "for": "Bug"
      },
      {
        "source": "environment",
        "source-type": "name",
        "target": "Microsoft.VSTS.TCM.SystemInfo"
      },
      {
        "source": "Reporter",
        "target": "Custom.Reporter",
        "mapper": "MapUser"
      },
      {
        "source": "Responsible AM",
        "target": "Custom.ResponsibleAM",
        "mapper": "MapUser"
      },
      {
        "source": "Account",
        "target": "Custom.Account",
        "mapper": "MapArray"
      },
      {
        "source": "Product Category",
        "target": "Custom.ProductCategory",
        "mapper": "MapArray"
      },
      {
        "source": "Component",
        "target": "Custom.Component",
        "mapper": "MapArray"
      },
      {
        "source": "Customer(s)",
        "target": "Custom.Customers",
        "mapper": "MapArray"
      },
      {
        "source": "Due Date",
        "source-type": "dateTime",
        "target": "Microsoft.VSTS.Scheduling.TargetDate"
      }
    ]
  }
}`

and here is a look at the users.txt

`<some guid>=user@domain.com
*=JiraAzureDevOps@domain.com`

**Comment by Alexander-Hjelm** [comment]
> I can tell you not all users from JIRA are available on ADO and user.txt as we had coworkers who left the organization.
For their accounts I used the default account option on the user.txt as in
*=JiraAzureDevOps@domain.com

In this case it will not resolve the mapping properly, unless you can a user explicitly with the email "JiraAzureDevOps@domain.com". You can try omitting the default (asterisk *) line in your user mapping. You should get the jira ids instead on the ADO side , and maybe that will help you debug.

> Sadly for my case the situation is not what you are presenting. Maybe there's an issue with my user.txt and its location.
Currently my users.txt is located in the same folder as where the jira workitems are being exported and I am using the same folder for the import (I am using the same config for the importer copy/paste)

The user mapping file should be inside the migration workspace (for you: `C:\Temp\JiraExport\`). Alternatively you can address it globally in the config.json. Try something like `C:\Temp\JiraExport\users.txt`

> Is the users.txt file case sensitive for email accounts?

Yes

> Does it have to be present somewhere else for the importer to read for comments?

Nope, should only be in the config

> Does not the default mapping in users.txt work for non existent users for comments? I could simply run the script with that robotic user anyways but it is interesting that it defaults to the token owner rather than the default which is set in the users.txt

Not sure about comments tbh, but some for operations (like creating new workitems) you cannot control who shows up in the work item history, it will be set to whoever ran the command.

Can you upload your migration logs here? You can drag-drop the txt-files into the issue to attach a file. Both the import and exports logs, preferably.

**Comment by omustapasa** [comment]
Hello again @Alexander-Hjelm,

I have anonymized the files and here they are.
Most of the errors are due to inactive user accounts and mappings not being found as a result of them not being available on ADO but a default.

[wi-import-log-220927-145018.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9682795/wi-import-log-220927-145018.txt)

[jira-export-log-220927-125646.txt](https://github.com/solidify/jira-azuredevops-migrator/files/9682796/jira-export-log-220927-125646.txt)

**Comment by Alexander-Hjelm** [comment]
I see that many of your user's have their email hidden, so the migrator will use the jira IDs instead of the emails. Try to map the user ID's instead (see the documentation on the config file or FAQ for examples), and see if that makes it better?

Also, which version of the jira migrator is this? I see a lot of this issue, but this was fixed on the master branch some time ago:

`[E][14:52:55] The identity value 'Microsoft.VisualStudio.Services.WebApi.IdentityRef' for field 'Assigned To' is an unknown identity.`

**Comment by omustapasa** [comment]
@Alexander-Hjelm 
My users.txt file only uses JIRA user IDs and AzureDevops email accounts.
Do you mean that I should use ADO accountId instead of ADO emails?

I am using the latest from master a week or two ago I believe.
It was suggested to use the latest from master instead of the release version due to a null reference exception.
I can get the latest from master and give it another go but need to understand how to fix the issue with comment owners.

I will try see if I can write a blog post of a step by step after I finish my migration ;)

**Comment by omustapasa** [comment]
@Alexander-Hjelm 
I can confirm with the latest master of today, comments are shown as per their respective owner! 
You can close this support ticket now I guess.

I am receiving exceptions regarding `TF401326: Invalid field status 'ReadOnly' for field 'System.BoardColumn'.`
Is it something that you have ever faced before?

**Comment by Alexander-Hjelm** [comment]
OK! Happy to hear :)

> I am receiving exceptions regarding TF401326: Invalid field status 'ReadOnly' for field 'System.BoardColumn'.
Is it something that you have ever faced before?

Nope, not for the jira-ado migrator specifically, but in other contexts yes. You aren't explicitly mapping System.BoardColumn though, so it shouldn't be an issue... It probably has something to do with the setup of your ADO boards.

No idea at the moment, but we'll have to keep an eye on it. If the issue causes you problems then feel free to open a new issue with a description :)
