### ISSUE TITLE
Custom IssueTypes on both ends fails to map

### ISSUE THREAD

**Issue by BenOberholzer** [solidify/jira-azuredevops-migrator#59]
In JIRA our team had created a 'Technical Debt' issuetype.  We similarly created a 'Technical Debt' issuetype in ADO.  I mapped the objects like I mapped any other object and ran the export.  In the individual export items, none of the standard fields (title, description, etc.) were created in the resulting JSON files for those issues.  Epics were created, bugs were created, etc.  I tried all sorts of variations of the issuetype name to no avail.  The only way I could work around it was to export those items to Bugs and then convert them after importing them to ADO.

Is this a limitation of custom to custom objects or possibly just a failure to look it up correctly?  I will try to review the code and see if I can find anything but I thought I'd ask first.

**Comment by MOlausson** [comment]
Hi @BenOberholzer I would expect this to work. Let's work to track this down.

**Comment by BenOberholzer** [comment]
No problem.  I have attached both here.
[jira-export-log-190530-095606.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3237303/jira-export-log-190530-095606.txt)
[config-swat.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3237304/config-swat.txt)

Apparently I can't post a json file so the config file is just changed to a .txt extension.

**Comment by MOlausson** [comment]
Thanks. Realized I would like to look at the import log as well. But the config looks fine at a first look.

**Comment by BenOberholzer** [comment]
[wi-import-log-190530-113754.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3237700/wi-import-log-190530-113754.txt)
Here's the import log.

**Comment by MOlausson** [comment]
@BenOberholzer did you get this resolved? I checked the logs and don't see the issue, perhaps these were for the files you have manually corrected?

**Comment by BenOberholzer** [comment]
@MOlausson I actually don't recall seeing errors during the import.  The items were created but most of the details (title, description, etc.) were missing.  It's like it couldn't map the fields on the import.  But then again the exported items from JIRA didn't have those details either.  I personally think the problem is on the export side, not the import.

**Comment by cia0mari** [comment]
@MOlausson I'm having same problem: I'm trying to export Bugs from Jira and importing them as Issues in DevOps but it fails. If I import them as Bugs in DevOps it works correctly.

**Comment by hacksoi** [comment]
I have the same problem too.

**Comment by ShadowXVII** [comment]
+1

**Comment by RubenOuwerkerk** [comment]
+1

**Comment by Jnaneshnayak** [comment]
+1

**Comment by quadmig** [comment]
+1
It does not give an error but it mostly doesn't load (see attachment0.
The exact same item and config imports correctly if the WIT is something else like product backlog item.
![customADOtype](https://user-images.githubusercontent.com/54333499/63461596-93d84d00-c41e-11e9-956a-64b0a289a906.JPG)

**Comment by jonada** [comment]
I have the same problem. No error or warning, but in the exported .json files several system fields were missing (not exported).

My workaround:
- Instead of exporting from Jira Task to DevOps Task, I configured it to export from Jira Task to DevOps Issue.
- After export, replaced “Task” for “Issue” at the beginning of all .json-files, for those work items that should be Issue instead of Task (since I exported several different types, not all files was to be replaced).

**Comment by ShadowXVII** [comment]
I tried using Issue instead of a custom work item type, but it still didn't export correctly. As soon as it's a custom type on either side, it seems to fail.

**Comment by kenjdavidson** [comment]
I ran into this issue as well, attempting to convert Jira BUG to DevOps ISSUE and found that the main problem stems from the WorkItemType (enum I guess) only containing a limited number of options, instead of actually being built from the configuration TypeMap. 

JiraExport.JiraMapper line 377 - The mappingPerWiType is being built statically with no reference to Issue, therefore if Bug is Mapped to issue, it's not finding a resulting field map and therefore not doing any conversion.

    var mappingPerWiType = new Dictionary<string, FieldMapping<JiraRevision>>
        {
            { WorkItemType.Bug, MergeMapping(commonFields, bugFields) },
            { WorkItemType.ProductBacklogItem, MergeMapping(commonFields, pbiFields) },
            { WorkItemType.Task, MergeMapping(commonFields, taskFields) },
            { WorkItemType.Feature, MergeMapping(commonFields, featureFields) },
            { WorkItemType.Epic, MergeMapping(commonFields, epicFields) },
            { WorkItemType.Requirement, MergeMapping(commonFields, requirementFields) },
            { WorkItemType.UserStory, MergeMapping(commonFields, userStoryFields) }
        };

Line 234 is failing:

    if (type != null && **_fieldMappingsPerType.TryGetValue(type, out var mapping)**)

Working under the assumption that we only care about Targets, which in my mind is a valid assumption since we're going to DevOps types.  I've made the following change to the InitializeFieldMappings method:

- create only those FieldMappings for Target types
- place FieldMappings into either Common or the appropriately named key
- For each TargetType merge field mappings with commonFields.

**Comment by MOlausson** [comment]
@kenjdavidson thanks for your feedback. Happy to review your code if you want to submit a PR.

**Comment by kmuthukumar-rp** [comment]
@MOlausson Any update on this issue. I am exporting Spike and Defect from Jira and mapping to same on ADO side. But the jira export json files does not have any fields or values in it and hence they are empty when imported into ADO. Doing the workaround that @jonada  mentioned will be too much as there are at least 500 jira spikes and defects exported. I have the latest release of the tool. Is there any other workaround or fix for it now or when can we expect it. Appreciate it a lot. Thank you.

**Comment by MOlausson** [comment]
Fixed from v.2.2.88
