### ISSUE TITLE
The value '[Insert Project Id]' does not exist for the field 'project'

### ISSUE THREAD

**Issue by tj-incycle** [solidify/jira-azuredevops-migrator#61]
I'm currently using the latest version, `2.2.25`, and migrating a series of projects and last night I started getting this error. No matter what project I try, I consistently get this error right now. I've verified the query I'm using works in Jira but doesn't work in the tool. Let me know what additional information you need for this.

```
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'COMOB' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'COMOB' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
```

**Comment by MOlausson** [comment]
@tj-incycle did you get this working?

**Comment by dlauryssen** [comment]
Hi,

I am having the same issue. I am not able to get the jira export working. For confidentiality purposes I have replaced the project name with XXXX. 

The query "project = XXXX" is working however in Jira. 

Jira Exporter v2.2.25
Copyright (c) Solidify
[I][17:08:42] Connecting to Jira...
[I][17:08:42] Retrieving Jira fields...
[I][17:08:43] Retrieving Jira link types...
[E][17:08:43] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'XXXX' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'XXX' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
[I][17:08:43] Export complete. Exported 0 items (1 errors, 0 warnings) in 00:00:00.




If I replace the query with "Status = Done" it does not throw an exception, however still not getting results and not sure if it is because I'm still not getting any items. 

Jira Exporter v2.2.25
Copyright (c) Solidify
[I][17:30:32] Connecting to Jira...
[I][17:30:32] Retrieving Jira fields...
[I][17:30:32] Retrieving Jira link types...
[I][17:30:32] Export started. Exporting 0 items.
[W][17:30:33] Epic link field missing for config field 'Epic Link'.
[W][17:30:33] Sprint link field missing for config field 'Sprint'.
[I][17:30:33] Initializing Jira field mapping...
[I][17:30:33] Export complete. Exported 0 items (0 errors, 2 warnings) in 00:00:01.


Please advise, as I want to moe forward with this as soon as possible. Many many thanks.

**Comment by MOlausson** [comment]
Hi @dlauryssen, can you provide the config setting for your JQL (something like this:   

"query": "project = SCRUM ORDER BY Rank ASC"

Also make sure the user/api token you are using has permissions to access the specified project.

**Comment by dlauryssen** [comment]
Hi @MOlausson, attached the config file I used with a query status = Done, 
[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/3436199/config.txt)
leading to the result 

> Jira Exporter v2.2.25
> Copyright (c) Solidify
> [I][16:39:26] Connecting to Jira...
> [I][16:39:26] Retrieving Jira fields...
> [I][16:39:27] Retrieving Jira link types...
> [I][16:39:28] Export started. Exporting 0 items.
> [W][16:39:28] Epic link field missing for config field 'Epic Link'.
> [W][16:39:28] Sprint link field missing for config field 'Sprint'.
> [I][16:39:28] Initializing Jira field mapping...
> [I][16:39:29] Export complete. Exported 0 items (0 errors, 2 warnings) in 00:00:03.

The api token is of my user, and I have access to the project. I can run all of the used queries in jira and they are having results. I'm copy pasting the query to the config file but not leading to any results when using "status = Done" or "project = longprojectname". Also tried shortprojectname, but not working of course. Also tried query names but obviously not working as expecting actual query. 

![image](https://user-images.githubusercontent.com/11612664/61960554-faa44b00-afc5-11e9-9014-d717fabc84e7.png)

I am using the following command C:\TEMP\jira migration installer>jira-export -u APITOKEN --url https://PROJECTURL.atlassian.net --config config.json

**Comment by dlauryssen** [comment]
@MOlausson interesting just tried with query   "query": "status = Done ORDER BY Rank ASC", with result

> Jira Exporter v2.2.25
> Copyright (c) Solidify
> [I][17:01:08] Connecting to Jira...
> [I][17:01:08] Retrieving Jira fields...
> [I][17:01:08] Retrieving Jira link types...
> [E][17:01:08] Unexpected migration error.
> [System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["Not able to sort using field 'Rank'."],"warningMessages":[]}
>    at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
>    at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at JiraExport.JiraProvider.GetItemCount(String jql)
>    at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
> ---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["Not able to sort using field 'Rank'."],"warningMessages":[]}
>    at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
>    at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()<---
> :
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at JiraExport.JiraProvider.GetItemCount(String jql)
>    at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
> [I][17:01:08] Export complete. Exported 0 items (1 errors, 0 warnings) in 00:00:00.

**Comment by MOlausson** [comment]
Thanks @dlauryssen for the additional info. I think the code (or the Jira api) expects a project in the query, haven't tested but can you try adding it to the query and see what happens? I.e

Project = PB AND status = Done ORDER BY Rank ASC

**Comment by dlauryssen** [comment]
@MOlausson no luck. 

I find it also strange that it says it is not able to sort by rank, like it doesn't recognize that column... 

[E][21:30:28] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'FB' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---

**Comment by dlauryssen** [comment]
also just tried it with 2.2.24 in stead of 25 but same behaviour.

**Comment by MOlausson** [comment]
I tested with the latest code (2.2.25) and this query works fine for me: Status = Done ORDER BY Rank ASC

Can you make sure it works if you run the same query from an advanced query view in Jira:

![image](https://user-images.githubusercontent.com/7904771/62043817-a2f22380-b201-11e9-91f7-92e7571a97c8.png)

**Comment by dlauryssen** [comment]
Yes it returns values 

![image](https://user-images.githubusercontent.com/11612664/62045304-5f99b400-b205-11e9-9307-7cb4af03d40b.png)

**Comment by dlauryssen** [comment]
[E][13:33:45] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()

**Comment by MOlausson** [comment]
What if you ignore the ORDER BY part?

**Comment by tj-incycle** [comment]
Sorry for the delay, I was away on vacation. I was able to get the tool to work without making any changes, all I did was simply change location. I was remote at a client's office when I got the error originally and opened the issue. When I returned back to my office it worked fine for me. I pulled the source code down and did a little debugging and I honestly feel like this issue is actually on Jira's API side. It almost seems like it is a region issue (like a load balancer sending you to a data center with out dated code) or maybe a proxy server messing with the content being sent? I honestly couldn't explain it.

**Comment by dlauryssen** [comment]
It goes through then, but no items found. But then starts complaining about Epic Link missing. 

[I][14:23:29] Connecting to Jira...
[I][14:23:29] Retrieving Jira fields...
[I][14:23:30] Retrieving Jira link types...
[I][14:23:30] Export started. Exporting 0 items.
[W][14:23:30] Epic link field missing for config field 'Epic Link'.
[W][14:23:30] Sprint link field missing for config field 'Sprint'.
[I][14:23:30] Initializing Jira field mapping...
[I][14:23:31] Export complete. Exported 0 items (0 errors, 2 warnings) in 00:00:01.

**Comment by dlauryssen** [comment]
just tried on the pc of a colleague and having the same (lack of) results; also tried using my personal hotspot, no luck. 

please also note that I'm having the same issue as https://github.com/solidify/jira-azuredevops-migrator/issues/3 that is why i am using an apitoken

also could this be related? https://community.atlassian.com/t5/Jira-Software-questions/REST-error-quot-The-value-XXX-does-not-exist-for-the-field/qaq-p/654730

**Comment by dlauryssen** [comment]
Issues solved. I was using the wrong parameters when using the apitoken. 

As mentioned above I was using the following command jira migration installer>jira-export -u APITOKEN --url https://PROJECTURL.atlassian.net --config config.json

while i should have been using the following command jira migration installer>jira-export -u emailaddress -p APITOKEN --url https://PROJECTURL.atlassian.net --config config.json

Thanks for the efforts

**Comment by MOlausson** [comment]
@dlauryssen great to hear you sorted it out! I'll look into improving the input validation so we can avoid going down the wrong path when troubleshooting. Thanks for your patience :)

**Comment by MOlausson** [comment]
@tj-incycle thanks for checking in and happy to hear it works for you. I'll add a story to improve input checks and potentially logging to make this kind of issue easier to spot.

**Comment by georgejeffery1989** [comment]
hi there
getting the same error message as above but think for different reasons. 

How do you configure this two;

"epic-link-field": "customfield_10008",
  "sprint-field": "customfield_10007",

Currently i get this warning message 

Epic link field missing for config field 'Epic Link'.
Sprint link field missing for config field 'Sprint'.
Thanks
George

**Comment by MOlausson** [comment]
@georgejeffery1989 does your Jira project use these Jira types? You can use this Jira api to get the list of fields and in there find the correct customfield: https://your_account.atlassian.net/rest/api/3/field.
