### ISSUE TITLE
Unable to authenticate to JIRA Server using "Authorization" header

### ISSUE THREAD

**Issue by jakeweidokal** [solidify/jira-azuredevops-migrator#658]
I am trying to use the JIRA export tool to connect to on-prem JIRA Server, but I am unable to authorize using username and password/PAT.

Our admins have the JIRA API setup so that we are not able to access the API using standard Basic Authentication. Instead, we must authenticate by passing a header on the request, formatted as `Authorization: Bearer <PAT>`. Is there a way to specify request headers for the JIRA API with this tool, and if not, can you add a way to do this so that I am able to authenticate?

**Comment by Alexander-Hjelm** [comment]
Basic authentication with the user password is deprecated, the recommended way by Atlassian is to authenticate with an API token.

The `Atlassian.Jira` package only supports authenticating with the username and API token. We would have to build our own Http client otherwise, which would be horrible from a maintenance standpoint.
