### ISSUE TITLE
Error while importing tickets to Azure

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#666]
I have successfully exported tickets from JIRA in .JSON files but getting errors while importing them to Azure project.
Adding log report for your reference:
[wi-import-log-230115-104126.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10419500/wi-import-log-230115-104126.txt)
Adding Jira export log file:
[jira-export-log-230115-104059.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10419501/jira-export-log-230115-104059.txt)
config scrum file:
[config-scrum (2).zip](https://github.com/solidify/jira-azuredevops-migrator/files/10419504/config-scrum.2.zip)

**Comment by Alexander-Hjelm** [comment]
What command are you using to invoke the importer?

Can you also attach the .json file for one of the failing exported workitems?

Have you read through the Overview.md and FAQ under docs before getting started with the migrator? The most common issues should be there.

**Comment by Alexander-Hjelm** [comment]
@Bikrammabzone We've just released https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.85, where we added more logging for exceptions raised by the **workitem create** endpoint. Using this, we managed to solve a related issue that my colleague ran into.

Try it and see if you can get more details about the error. Most likely it is due to some misconfiguration on the ADO process :)
