### ISSUE TITLE
Assignee's not getting migrated

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#669]
Is the format correct? Attached users.txt
[users.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10425537/users.txt)

**Comment by Alexander-Hjelm** [comment]
Looks correct! Depending on how you have configured your JIRA instance, the API will use either the emails or IDs as user identifiers.

It could be that you need to supply the **username** or **id** of the user instead of the email. You can find these on the User page (user settings) in Jira, or via the User Lookup API endpoint. Try it!

On the ADO side, you should always specify the **uniqueName** of the user. This is usually the email.
