### ISSUE TITLE
Assignee names not getting mapped, instead their JIRA id's are 

### ISSUE THREAD

**Issue by Bikrammabzone** [solidify/jira-azuredevops-migrator#689]
![Screenshot (93)](https://user-images.githubusercontent.com/121940137/217444082-f672cc7b-d066-4315-94e6-171f905e7fb5.png)
Assignee's name or email is not showing up even after mapping in users.txt doc. Instead, JIRA id's are being shown. Please look into @Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
@Bikrammabzone, you must map the user IDs first. Check the docs :)

**Comment by Bikrammabzone** [comment]
Fixed, thanks

**Comment by Alexander-Hjelm** [comment]
Perfect! Closing :)

**Comment by btbowden** [comment]
I have a similair problem, but the email from Jira is getting mapped versus the Azure email/id on the imported items even though I have that user mapped, see below.  After import it shows bobby.bowden@source.com instead of bobby.bowden@destination.net

bobby.bowden@source.com=Bobby.Bowden@destination.net

**Comment by Alexander-Hjelm** [comment]
@btbowden please create a new support issuse
