### ISSUE TITLE
Migrating multiple Jira Projects. Export/Import separately, or en masse?

### ISSUE THREAD

**Issue by AnthonyRobinson** [solidify/jira-azuredevops-migrator#835]
This is less a problem and more of a "How to migrate multiple, inter-project-referencing Jira Projects into ADO" workflow recommendation request.

I have many Jira projects I am migrating into ADO. Some of the issues in these Jira projects link to issues in other Jira projects.  Upon export/import, I assume these relationships are lost, as the linked items are in projects (ADO Project level) that don't exist yet.  Even if they did exist in ADO, I'm not sure how they would be found.  The Jira keys are lost post-import and replaced with 

Would combining all the exports of all the Jira Project into a single monolithic import folder help at all?

Is there a recommended workflow for this type of migration?

**Comment by Alexander-Hjelm** [comment]
This should be taken care of by the `itemsJournal.txt`, and in that case you will not need any additional strategy. Simply migrate one project after another, and as long as you preserve the `itemsJournal.txt` file in the migration workspace you should be safe.

However, if I remember correctly, some people have reported that this feature does not work properly at the moment. But I am not sure if that is due to a bug in the tool or improper configuration.

You are welcome to give it a try on some sample projects. Let me know the results and let's take it from there!

**Comment by AnthonyRobinson** [comment]
A couple of follow-up questions:

- Am I correct in assuming that the itemsJournal.txt file will also prevent the creation of duplicates in ADO?
- In the case of getting good Jira inter-project linking in ADO, does the order of import matter? 

Thanks for your help.

**Comment by Alexander-Hjelm** [comment]
> Am I correct in assuming that the itemsJournal.txt file will also prevent the creation of duplicates in ADO?

Nope. At least as far as I have observed, you will still get work item duplicates if you chose to import the same project again, so better clear the target ADO project of all work items before you start over. Personally I'm not sure if this functionality is desirable or not. It could be that we choose to create a configuration flag that enables this feature, so that you could opt-in to omit work items that already have been imported.

> In the case of getting good Jira inter-project linking in ADO, does the order of import matter?

No the order should not matter :)

**Comment by AnthonyRobinson** [comment]
Good catch. I'll do some testing without --force.  Thanks!
