### ISSUE TITLE
What security methods are used in the migrator to protect data during migration?

### ISSUE THREAD

**Issue by rrobertsor** [solidify/jira-azuredevops-migrator#953]
We are evaluating whether this is a solution for us and for our Info Sec crew to approve we need to see some security details for this app. 

Where may I find those? Or can you send to me? 

Thanks!

**Comment by Alexander-Hjelm** [comment]
Hi @rrobertsor 

I will paste all of the security details available below. If you can any further specific questions, feel free to comment and I'll answer to the best of my ability :)

### Development details

- Which programming language is used?

  .NET Framework (C#)

- Are third party components or plugins used?

  Here is a list of the top-level NuGet packages used by the solution as of 2023-09-03:

  | Top-level Package                      | Version     |
  |----------------------------------------|-------------|
  | Atlassian.SDK                          | 12.1.0      |
  | AutoFixture                            | 4.11.0      |
  | AutoFixture.AutoNSubstitute            | 4.11.0      |
  | coverlet.collector                     | 3.1.2       |
  | Microsoft.NET.Test.Sdk                 | 16.5.0      |
  | Microsoft.TeamFoundationServer.Client  | 16.153.0    |
  | Newtonsoft.Json                        | 13.0.1      |
  | NSubstitute                            | 4.2.1       |
  | NUnit                                  | 3.12.0      |
  | NUnit.Analyzers                        | 3.3.0       |
  | NUnit3TestAdapter                      | 4.2.1       |
  | System.IO.Abstractions                 | 17.0.11     |

- Does the application use web services or APIs?

  The solution uses the following web APIs:

  - Azure DevOps Services/Server REST API (<https://learn.microsoft.com/en-us/rest/api/azure/devops>)
  - Jira REST API (<https://developer.atlassian.com/server/jira/platform/rest-apis/>)
  - Azure Applications Insights API for telemetry (Can be turned off)

### Network security

- How will data integrity be ensured during the migration?

  - The integrity of the Jira data is ensured by the tool.
  - Project reader access is sufficient in Jira.

- How do you ensure the security of data during migration?

  - The data will be exported to disk. If necessary, the migration should be carried out on an on-premises environment to ensure full compliance. If so, the customer needs to provision an environment.

- Does the solution have encryption in transit? (SSL/TLS)

  https is supported for all network traffic.

- Does the solution have encryption at rest? (file or disk)

  The tool does not provide any encryption at rest service.

- Does the solution have encryption/obfuscation while processing? (P2PE)

   The tool does not provide any P2PE service.

- Has the code base gone through a static code review for OWASP top 10 and/or SANS25?

  The tool frequently undergoes OWASP top 10 static code analysis through Sonarqube.

- Has the app gone through a DAST or other dynamic testing?

  No

- Are there any hard-coded passwords within the code base?

  No

- Does the application have the ability to prevent duplicate concurrent sessions per user?

  No

- Does the application have the ability to limit the total number of active sessions?

  No

- Does the application have the ability to automatically tear down/terminate sessions and logout after a defined time is exceeded?

  No

- Does the application validate ALL input, regardless of the source, when it crosses a trust boundary?

  The application validates any user input parameters and configuration for the purpose of ensuring that the program can execute normally.

- Is the application SAML 2.0 compatible? Is the application able to integrate with Active Directory?

  The application does not integrate with Active Directory or SAML. The user will instead provide their API tokens for the respective services in order to authenticate.
