### ISSUE TITLE
Comments with the user mentions show ugly as [~accountid:XXXXXXXX]

### ISSUE THREAD

**Issue by ValekMal** [solidify/jira-azuredevops-migrator#96]
When migrating comments, it would be great to migrate the user **mentions** correctly by either:

- trying to map to the DevOps users and insert the correct mention using the @ sign.
- just include the display name of the JIRA user. At lest it will look more readable

Example:
JIRA comment was: FYI @john123321123 and @peter123321123
DevOps comment is: FYI [~accountid:xxxxxxxxxxxxxxxxxxxx] and [~accountid:yyyyyyyyyyyyyyyyyyy]

**Comment by sanjeev40084** [comment]
@ValekMal even we noticed the same behavior while migrating jira project to DevOps. When we use mention '@' in DevOps it sends notification to mentioned user. I believe the dev. might have done that so that mentioned user done end up getting tons of notification once the project gets migrated to DevOps...just a thought.

**Comment by MOlausson** [comment]
Fixed from r.2.2.57.
