### ISSUE TITLE
VS402625: Dates must be increasing with each revision.

### ISSUE THREAD

**Issue by dhananjaykumar-pathak** [solidify/jira-azuredevops-migrator#968]
Problem:

While running the wi-import tool for Azure Devops migration, I'm getting this error for many work items. 

VS402625: Dates must be increasing with each revision. Work item failed to save.

**Tool version**
 - Version of the jira-azuredevops-migrator tool [3.0.284]

Attached are the config.json and the import and export logs. Also the screenshot of the error while debugging is attached.
[wi-import-log-240119-115925.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13986968/wi-import-log-240119-115925.txt)
 
[jira-export Bug_Fixed_Resolved_Minor.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13986971/jira-export.Bug_Fixed_Resolved_Minor.txt)
[config.json for reference excluding the project names and jql query.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13986992/config.json.for.reference.excluding.the.project.names.and.jql.query.txt)

**Comment by eplnde** [comment]
I have noticed this problem when I are doing re-imports and someone have done changes on the previously imported AzDo item.
So check Work Item 844131 in AzDo and see if someone have made any changes there
Not a solution, just a suggestion on how to understand the problem better

I am also very interested in how to handle this type of change conflict problems...

**Comment by Alexander-Hjelm** [comment]
I would start by looking into WECLAPP-24078.json and check if there are any revisions that have a timestamp that is earlier than the previous revision. Likely a link has been added to WECLAPP-24078 via another issue, and the order of events have been reversed in the changelog. Maybe a workaround could be to manually edit the timestamp so that the chronological order of the revisions is preserved=

This has been an ongoing problem, because the Jira Changelog can get messed up like this in so many ways. Identifying all of the possible edge cases is quite a pain. :/
