### ISSUE TITLE
All Images shown as 'broken image' icon. (And if I can access them, they images have a Jira URL) (same Issue as #887?)

### ISSUE THREAD

**Issue by steverwyllie** [solidify/jira-azuredevops-migrator#992]
**Describe the problem**
(1) Broken Images..... When the ADO Work Item is opened, I see the 'broken image' icon instead of the images.
(2) With a Jira url..... I can see them by  clicking Open Image in New Tab - but they have a Jira url.
The broken images are a difficult usability issue, but the Jira Server is going to be removed in about a week, so I'm also worried the images will be unavailable

**To Reproduce**
When I open an ADO Work Item created by the Migrator, I see the 'broken image' icon instead of the images.
When I then hover over the broken-image icon, right-click and select
 -- Load Image - nothing happens
 -- Open Image in New Tab - the image is presented, but with a url that 'points' to the original Jira Server
I'd like to see the images instead of the 'broken-image' icon, but the Jira Server is going to be removed in about a week, so I'm also worried the images will then become entirely unavailable

**Tool version**
 - 3.0.356

**Attachments**

- config.json
[config-scrum.json](https://github.com/solidify/jira-azuredevops-migrator/files/14388885/config-scrum.json)

- jira-export-log.txt
[jira-export-log-240223-182843.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14388887/jira-export-log-240223-182843.txt)

- wi-import-log.txt
[wi-import-log-240223-182859.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14388890/wi-import-log-240223-182859.txt)

**Screenshots**
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/4835941/c58fea5e-6e23-4fe6-a243-3c05a6042202)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/4835941/20cd625e-ecaa-4a15-9d8d-cf828c6fbdc9)
![image](https://github.com/solidify/jira-azuredevops-migrator/assets/4835941/9f33929a-ff3d-431a-81e0-be81b9a3ff53)

**Comment by Alexander-Hjelm** [comment]
Here are some steps to try:

- In your migration workspace, locate the .png image in the Attachments/ folder and verify that the .png image is rendering correctly on your local machine or VDI.
- Are the .png images imported on the Work Item as Attachments? If so, can you maybe see what the discrepancy is between the attachment URLs and the URLs in the Work Item Description?

Otherwise here are some potentially related issues:

- https://github.com/solidify/jira-azuredevops-migrator/issues/986
- https://github.com/solidify/jira-azuredevops-migrator/issues/851
